"""
SQLAlchemy ORM models — the database schema for the bridge inspection system.

The schema is designed around how bridge inspection data naturally flows:

    County → Bridge → Inspection → (Defects, Recommendations, Images)
                                     ↑ extracted by AI agents

    Bridge/County → Insight
                     ↑ generated by analysis agents

Key design decisions:
  - Bridge is the central entity. It has a fixed identity (structure_number)
    and physical attributes that rarely change.
  - Inspections are time-series data linked to a bridge. Each row represents
    one year's NBI submission. This enables year-over-year trend analysis.
  - Defects and Recommendations are extracted from inspection report text by
    LLM agents. The `source` field tracks provenance (llm vs manual).
  - Insights are generated by analysis agents and can link to a specific
    bridge, a county, or neither (network-wide insights).

NBI reference: https://www.fhwa.dot.gov/bridge/nbi/format.cfm
"""
from datetime import date, datetime
from typing import Optional
import json

from sqlalchemy import (
    Boolean, Column, Date, DateTime, Float, ForeignKey,
    Integer, String, Text, JSON, UniqueConstraint, Index
)
from sqlalchemy.orm import DeclarativeBase, relationship
from sqlalchemy.sql import func


class Base(DeclarativeBase):
    """Base class for all ORM models. SQLAlchemy 2.0 style."""
    pass


# =============================================================================
# County
# =============================================================================

class County(Base):
    """
    A Minnesota county that contains bridges.

    We selected 5 target counties (see config.py for rationale).
    The FIPS code is the 3-digit federal identifier used in NBI data
    to identify which county a bridge belongs to.
    """
    __tablename__ = "counties"

    id = Column(Integer, primary_key=True, autoincrement=True)
    fips_code = Column(String(3), unique=True, nullable=False)  # e.g. "053" for Hennepin
    name = Column(String(100), nullable=False)                   # e.g. "Hennepin"
    state = Column(String(2), nullable=False, default="MN")

    # Relationships — navigate from a county to its bridges or insights
    bridges = relationship("Bridge", back_populates="county")
    insights = relationship("Insight", back_populates="county")

    def __repr__(self):
        return f"<County {self.name} ({self.fips_code})>"


# =============================================================================
# Bridge
# =============================================================================

class Bridge(Base):
    """
    A physical bridge structure.

    The structure_number is the NBI's unique identifier for each bridge.
    Physical attributes (material, dimensions, location) are stored here
    because they don't change between inspections (or change rarely).

    When the same bridge appears in multiple years of NBI data, we update
    these fields with the most recent values (see parse_nbi_data.py).
    """
    __tablename__ = "bridges"

    id = Column(Integer, primary_key=True, autoincrement=True)
    structure_number = Column(String(20), unique=True, nullable=False)  # NBI Item 8
    county_id = Column(Integer, ForeignKey("counties.id"), nullable=False)

    # -- Location (NBI Items 16/17) -------------------------------------------
    # Stored as decimal degrees for easy mapping (Leaflet, GeoJSON).
    # NBI raw format is degrees-minutes-seconds; we convert during parsing.
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)

    # -- Identity (NBI Items 5, 6, 7) ----------------------------------------
    facility_carried = Column(String(200), nullable=True)       # Road/feature ON the bridge
    feature_intersected = Column(String(200), nullable=True)    # What the bridge crosses
    location_description = Column(String(200), nullable=True)   # Free-text location
    owner_code = Column(String(2), nullable=True)               # NBI Item 21 (raw code)
    owner_name = Column(String(100), nullable=True)             # Human-readable owner name

    # -- Physical Characteristics ---------------------------------------------
    year_built = Column(Integer, nullable=True)                  # NBI Item 27
    year_reconstructed = Column(Integer, nullable=True)          # NBI Item 106
    material_code = Column(String(2), nullable=True)             # NBI Item 43A (raw code)
    material_name = Column(String(100), nullable=True)           # e.g. "Prestressed Concrete"
    design_code = Column(String(2), nullable=True)               # NBI Item 43B (raw code)
    design_name = Column(String(100), nullable=True)             # e.g. "Stringer/Multi-beam"
    number_of_spans = Column(Integer, nullable=True)             # NBI Item 45
    structure_length = Column(Float, nullable=True)              # Meters — NBI Item 49
    deck_width = Column(Float, nullable=True)                    # Meters — NBI Item 52
    approach_span_material = Column(String(2), nullable=True)    # NBI Item 44A
    approach_span_design = Column(String(2), nullable=True)      # NBI Item 44B
    number_approach_spans = Column(Integer, nullable=True)       # NBI Item 46

    # -- Traffic Data (NBI Items 29, 109) ------------------------------------
    # ADT (Average Daily Traffic) is critical for risk prioritization:
    # a failing bridge carrying 50,000 cars/day is far more urgent than
    # one carrying 200 cars/day.
    adt = Column(Integer, nullable=True)
    adt_year = Column(Integer, nullable=True)       # Year the ADT count was taken
    truck_pct = Column(Float, nullable=True)         # Percentage of ADT that is trucks
    functional_class = Column(String(2), nullable=True)  # NBI Item 26 (interstate, arterial, etc.)

    # -- Relationships --------------------------------------------------------
    county = relationship("County", back_populates="bridges")
    inspections = relationship("Inspection", back_populates="bridge",
                               order_by="Inspection.data_year")  # Chronological order
    insights = relationship("Insight", back_populates="bridge")

    def __repr__(self):
        return f"<Bridge {self.structure_number} - {self.facility_carried}>"


# =============================================================================
# Inspection (Time-Series Core)
# =============================================================================

class Inspection(Base):
    """
    One year's inspection record for a bridge.

    This is the time-series backbone of the system. Each bridge has one
    Inspection row per NBI data year (2023, 2024, 2025). The UniqueConstraint
    on (bridge_id, data_year) prevents duplicate entries.

    The NBI condition ratings (Items 58-62) use a 0-9 scale:
      9 = Excellent, 7 = Good, 5 = Fair, 4 = Poor, 0 = Failed
    A bridge is "Structurally Deficient" if any rating ≤ 4.

    We also store computed fields (min_condition, health_index) to avoid
    recalculating them on every API request.
    """
    __tablename__ = "inspections"
    __table_args__ = (
        # Prevent duplicate inspection records for the same bridge + year
        UniqueConstraint("bridge_id", "data_year", name="uq_bridge_year"),
        # This composite index speeds up the most common query pattern:
        # "get all inspections for bridge X, ordered by year"
        Index("ix_inspections_bridge_year", "bridge_id", "data_year"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    bridge_id = Column(Integer, ForeignKey("bridges.id"), nullable=False)
    data_year = Column(Integer, nullable=False)          # Which NBI annual file this came from
    inspection_date = Column(String(6), nullable=True)   # MMYYYY format from NBI Item 90

    # -- NBI Condition Ratings (0-9 scale) ------------------------------------
    # These are the core health indicators. Each rates a major component.
    # "N" (not applicable) is stored as None/NULL.
    deck_condition = Column(Integer, nullable=True)             # Item 58 — riding surface
    superstructure_condition = Column(Integer, nullable=True)    # Item 59 — beams/girders
    substructure_condition = Column(Integer, nullable=True)      # Item 60 — piers/abutments
    culvert_condition = Column(Integer, nullable=True)           # Item 62 — for culvert-type bridges
    channel_condition = Column(Integer, nullable=True)           # Item 61 — waterway beneath
    channel_protection = Column(Integer, nullable=True)          # Item 61 sub-field

    # -- Appraisal Ratings (NBI Items 67-71) ----------------------------------
    # These evaluate the bridge's adequacy for current needs (not just condition).
    structural_eval = Column(Integer, nullable=True)        # Item 67
    deck_geometry_eval = Column(Integer, nullable=True)     # Item 68 — is the deck wide enough?
    underclearance_eval = Column(Integer, nullable=True)     # Item 69 — enough room underneath?
    waterway_adequacy = Column(Integer, nullable=True)       # Item 70 — flooding risk
    approach_alignment = Column(Integer, nullable=True)      # Item 71 — road alignment quality

    # -- Load Ratings (NBI Items 64, 66) --------------------------------------
    # The maximum weight the bridge can safely carry, in metric tons.
    # Operating = absolute max with permit; Inventory = safe for routine traffic.
    operating_rating = Column(Float, nullable=True)    # Metric tons
    inventory_rating = Column(Float, nullable=True)    # Metric tons
    sufficiency_rating = Column(Float, nullable=True)  # Item 68 — composite score (0-100)

    # -- Status Flags ---------------------------------------------------------
    structurally_deficient = Column(Boolean, nullable=True)  # True if any condition ≤ 4
    sd_fo_status = Column(String(2), nullable=True)          # Raw NBI code

    # -- Computed/Derived Fields ----------------------------------------------
    # Pre-computed during data loading to speed up dashboard queries.
    min_condition = Column(Integer, nullable=True)  # Worst of deck/super/sub — quick "health at a glance"
    health_index = Column(Float, nullable=True)     # Weighted composite 0-100 (see parse_nbi_data.py)

    # -- Free-Text (from PDF reports, if available) ---------------------------
    inspector_notes = Column(Text, nullable=True)

    # -- Relationships --------------------------------------------------------
    bridge = relationship("Bridge", back_populates="inspections")
    elements = relationship("ElementInspection", back_populates="inspection")
    defects = relationship("Defect", back_populates="inspection")
    recommendations = relationship("Recommendation", back_populates="inspection")
    images = relationship("InspectionImage", back_populates="inspection")

    def __repr__(self):
        return f"<Inspection bridge={self.bridge_id} year={self.data_year}>"


# =============================================================================
# Element Inspection (Granular Component Data)
# =============================================================================

class ElementInspection(Base):
    """
    Element-level inspection data (FHWA Element Data, not regular NBI).

    While NBI gives coarse 0-9 ratings for major components, the element-level
    data breaks bridges into specific elements (e.g., "Element 12: Reinforced
    Concrete Deck") and reports the quantity in each of 4 condition states.

    Example: A deck with 500 sq ft total might have:
      CS1 (good): 350 sq ft, CS2 (fair): 100, CS3 (poor): 40, CS4 (severe): 10

    This granularity lets us track exactly how much of each element is
    deteriorating, which is more powerful than a single 0-9 number.
    """
    __tablename__ = "element_inspections"

    id = Column(Integer, primary_key=True, autoincrement=True)
    inspection_id = Column(Integer, ForeignKey("inspections.id"), nullable=False)
    element_number = Column(Integer, nullable=False)          # FHWA element code
    element_description = Column(String(200), nullable=True)  # Human-readable name
    total_quantity = Column(Float, nullable=True)
    unit = Column(String(20), nullable=True)                  # "each", "linear ft", "sq ft"
    cs1_quantity = Column(Float, nullable=True)   # Condition State 1 — best condition
    cs2_quantity = Column(Float, nullable=True)   # Condition State 2
    cs3_quantity = Column(Float, nullable=True)   # Condition State 3
    cs4_quantity = Column(Float, nullable=True)   # Condition State 4 — worst condition

    inspection = relationship("Inspection", back_populates="elements")


# =============================================================================
# Defect (LLM-Extracted from Inspection Reports)
# =============================================================================

class Defect(Base):
    """
    A specific defect identified in a bridge inspection.

    These records are created by the Defect Classification Agent, which
    uses an LLM to extract structured defect information from free-text
    inspection notes in PDF reports.

    The `source` field provides traceability — an important concern for
    engineering tools where decisions must be auditable. It tells us whether
    the defect was extracted by an LLM or entered manually by an engineer.
    """
    __tablename__ = "defects"

    id = Column(Integer, primary_key=True, autoincrement=True)
    inspection_id = Column(Integer, ForeignKey("inspections.id"), nullable=False)
    defect_type = Column(String(100), nullable=True)     # cracking, spalling, corrosion, scour, etc.
    severity = Column(String(20), nullable=True)          # minor, moderate, severe, critical
    component = Column(String(100), nullable=True)        # deck, superstructure, substructure, joint, etc.
    description = Column(Text, nullable=True)             # Full defect description
    location_on_bridge = Column(Text, nullable=True)      # Where on the bridge (e.g., "span 3, south pier")
    source = Column(String(20), default="llm")            # "llm" or "manual" — for audit traceability

    inspection = relationship("Inspection", back_populates="defects")


# =============================================================================
# Recommendation (LLM-Extracted from Inspection Reports)
# =============================================================================

class Recommendation(Base):
    """
    A maintenance or repair recommendation from an inspection report.

    Extracted by the Recommendation Extractor Agent from PDF report text.
    Priority levels follow standard bridge maintenance categories:
      - routine: regular maintenance (cleaning, sweeping)
      - preventive: stop deterioration (sealing, painting)
      - corrective: fix existing damage (patching, repairs)
      - urgent: immediate safety concern (load posting, closure)
    """
    __tablename__ = "recommendations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    inspection_id = Column(Integer, ForeignKey("inspections.id"), nullable=False)
    priority_level = Column(String(20), nullable=True)     # routine, preventive, corrective, urgent
    action_description = Column(Text, nullable=True)       # What needs to be done
    category = Column(String(100), nullable=True)           # paint, repair, replace, monitor, restrict, close
    estimated_cost = Column(Float, nullable=True)           # Estimated cost in USD (if mentioned)
    source = Column(String(20), default="llm")             # Audit trail: who created this record

    inspection = relationship("Inspection", back_populates="recommendations")


# =============================================================================
# Inspection Image (Extracted from PDF Reports)
# =============================================================================

class InspectionImage(Base):
    """
    A photo extracted from a bridge inspection PDF report.

    Bridge inspection reports typically include photos showing:
      - Overall bridge views (upstream, downstream, underside)
      - Specific defects (cracks, rust, spalling, scour)
      - Measurement reference points

    Images are extracted from PDFs using PyMuPDF and stored on disk.
    This table tracks their location and metadata.
    """
    __tablename__ = "inspection_images"

    id = Column(Integer, primary_key=True, autoincrement=True)
    inspection_id = Column(Integer, ForeignKey("inspections.id"), nullable=False)
    file_path = Column(String(500), nullable=True)         # Path to extracted image file
    caption = Column(Text, nullable=True)                   # Image caption from the PDF
    component_shown = Column(String(100), nullable=True)   # Which bridge component is in the photo
    page_number = Column(Integer, nullable=True)            # Source page in the PDF

    inspection = relationship("Inspection", back_populates="images")


# =============================================================================
# Insight (Generated by Analysis Agents)
# =============================================================================

class Insight(Base):
    """
    An engineering or operational insight generated by an analysis agent.

    This is the output of Phase 3 of the pipeline. Analysis agents examine
    the accumulated inspection data and produce actionable insights like:
      - "Bridge X shows accelerating deck deterioration (7→5→3 over 3 years)"
      - "Concrete bridges in St. Louis County degrade 40% faster than steel"
      - "County Y has 12 bridges at risk of falling below 'Fair' within 2 years"

    Design decisions:
      - bridge_id and county_id are nullable because some insights are
        network-wide (not tied to a specific bridge or county).
      - supporting_data is a JSON field for storing chart data, statistics,
        or lists that the frontend can render (e.g., a time series for a trend chart).
      - confidence_score (0.0-1.0) lets the UI sort/filter by reliability.
      - severity helps color-code insights (info=blue, warning=orange, critical=red).
    """
    __tablename__ = "insights"

    id = Column(Integer, primary_key=True, autoincrement=True)
    insight_type = Column(String(50), nullable=False)       # "trend", "risk", "pattern"
    agent_name = Column(String(100), nullable=False)        # Which agent generated this
    bridge_id = Column(Integer, ForeignKey("bridges.id"), nullable=True)   # Nullable: network-level insights
    county_id = Column(Integer, ForeignKey("counties.id"), nullable=True)  # Nullable: cross-county insights
    title = Column(String(300), nullable=False)             # Short headline for the dashboard
    description = Column(Text, nullable=False)              # Detailed explanation
    supporting_data = Column(JSON, nullable=True)           # Structured data for charts/tables
    confidence_score = Column(Float, nullable=True)         # 0.0 (low) to 1.0 (high)
    severity = Column(String(20), nullable=True)            # info, warning, critical
    generated_at = Column(DateTime, server_default=func.now())

    bridge = relationship("Bridge", back_populates="insights")
    county = relationship("County", back_populates="insights")

    def __repr__(self):
        return f"<Insight [{self.insight_type}] {self.title[:50]}>"
